export const expensesData = [
  {
    id: 1,
    expenseId: 1,
    category: {
      id: 2,
      name: "Casa",
      color: "#3b6e40",
      icon: {
        iconName: "house",
        iconSet: "MaterialIcons",
      },
    },
    name: "Pago de renta",
    date: "2024-03-01T10:00:00",
    quantity: 1000,
    description: "Pago mensual de renta.",
    image: "https://example.com/renta.png",
  },
  {
    id: 2,
    expenseId: 2,
    category: {
      id: 3,
      name: "Comida",
      color: "#d9534f",
      icon: {
        iconName: "restaurant",
        iconSet: "MaterialIcons",
      },
    },
    name: "Supermercado",
    date: "2024-03-02T12:30:00",
    quantity: 150,
    description: "Compras de la semana en el supermercado.",
    image: "https://example.com/supermercado.png",
  },
  {
    id: 3,
    expenseId: 3,
    category: {
      id: 4,
      name: "Transporte",
      color: "#0275d8",
      icon: {
        iconName: "directions_car",
        iconSet: "MaterialIcons",
      },
    },
    name: "Gasolina",
    date: "2024-03-03T09:15:00",
    quantity: 80,
    description: "Llenado de tanque de gasolina.",
    image: "https://example.com/gasolina.png",
  },
  {
    id: 4,
    expenseId: 4,
    category: {
      id: 5,
      name: "Entretenimiento",
      color: "#f0ad4e",
      icon: {
        iconName: "theater_comedy",
        iconSet: "MaterialIcons",
      },
    },
    name: "Netflix",
    date: "2024-03-04T18:00:00",
    quantity: 10,
    description: "Suscripción mensual de Netflix.",
    image: "https://example.com/netflix.png",
  },
  {
    id: 5,
    expenseId: 5,
    category: {
      id: 6,
      name: "Salud",
      color: "#d9534f",
      icon: {
        iconName: "local_hospital",
        iconSet: "MaterialIcons",
      },
    },
    name: "Consulta médica",
    date: "2024-03-05T16:00:00",
    quantity: 50,
    description: "Consulta con el doctor general.",
    image: "https://example.com/medico.png",
  },
  {
    id: 6,
    expenseId: 6,
    category: {
      id: 7,
      name: "Educación",
      color: "#5bc0de",
      icon: {
        iconName: "school",
        iconSet: "MaterialIcons",
      },
    },
    name: "Curso en línea",
    date: "2024-03-06T20:00:00",
    quantity: 30,
    description: "Pago de un curso en línea.",
    image: "https://example.com/curso.png",
  },
  {
    id: 7,
    expenseId: 7,
    category: {
      id: 8,
      name: "Ropa",
      color: "#795548",
      icon: {
        iconName: "shopping_bag",
        iconSet: "MaterialIcons",
      },
    },
    name: "Compra de ropa",
    date: "2024-03-07T15:00:00",
    quantity: 75,
    description: "Compra de ropa nueva en tienda.",
    image: "https://example.com/ropa.png",
  },
  {
    id: 8,
    expenseId: 8,
    category: {
      id: 9,
      name: "Mascotas",
      color: "#ff9800",
      icon: {
        iconName: "pets",
        iconSet: "MaterialIcons",
      },
    },
    name: "Alimento para perro",
    date: "2024-03-08T13:00:00",
    quantity: 40,
    description: "Saco de alimento para el perro.",
    image: "https://example.com/mascotas.png",
  },
  {
    id: 9,
    expenseId: 9,
    category: {
      id: 10,
      name: "Tecnología",
      color: "#673ab7",
      icon: {
        iconName: "devices",
        iconSet: "MaterialIcons",
      },
    },
    name: "Mouse inalámbrico",
    date: "2024-03-09T10:30:00",
    quantity: 25,
    description: "Compra de mouse para la laptop.",
    image: "https://example.com/mouse.png",
  },
  {
    id: 10,
    expenseId: 10,
    category: {
      id: 11,
      name: "Deportes",
      color: "#4caf50",
      icon: {
        iconName: "sports_soccer",
        iconSet: "MaterialIcons",
      },
    },
    name: "Membresía gimnasio",
    date: "2024-03-10T07:00:00",
    quantity: 50,
    description: "Pago mensual del gimnasio.",
    image: "https://example.com/gimnasio.png",
  },
];
